### ISSUE TITLE
d3helper v16.08.17 beta and newer, AutoGamble doesnt work anymore

### ISSUE THREAD

**Issue by DaLeberkasPepi** [r3peat/D3Helper.Public#11]
Like stated in the description the AutoGamble Function doesn't work anymore atleast since version d3helper v16.08.17

**Comment by Enigma32** [comment]
I've updated the GetCurrency method (https://github.com/Enigma32/Enigma.D3/commit/309f4a57681003c446fc783437670e45116dc4f0). Perhaps that solves the issue.

**Comment by d2k2-git** [comment]
yes, seems autogamble works again with this fix. not working perfect, but it works +1:
