### ISSUE TITLE
Overlay Function - Riftprogress

### ISSUE THREAD

**Issue by DaLeberkasPepi** [r3peat/D3Helper.Public#9]
The Overlay Function for Riftprogress doesn't seem to be up to date. It shows at the same range setting more progress then TurboHUD

**Comment by DaLeberkasPepi** [comment]
is it possible to gather the mob progression data from the game itself using enigma engine? @Enigma32 @d2k2-git

**Comment by Enigma32** [comment]
I guess the current values came from the assets (SNOs) so yea. But I don't know where and will not investigate. Someone else might.
